### ISSUE TITLE
[suggestion] close and still run on the background

### ISSUE THREAD

**Issue by dgrips** [Monochromish/Last.fm-Discord-Rich-Presence#5]
hi! thank you so much for this! i love showing what im listening to, thank you very much, to a music lover to another.
in my opinion, to make it even better than it already is would be if you could close the app, minimizing it to the task tray. also would really love if the api keys didnt need to be reset everytime i open the program. if theres already a way to do this, please do tell! im not tech savvy and would need some help doing it...
still, thank you so much for the app, its very very cool! much love!

**Comment by Monochromish** [comment]
I don't work much on this app anymore but I'll add the minimise to tray option.

**Comment by Monochromish** [comment]
The latest release does what you had asked for, closing this issue.
